#!/bin/bash
source ./cloudbees-demo.config

main() {
  echo "-----"
  if [[ "$1" == "del" ]]; then
    delete_jenkins
  fi
#  build_jenkins
  start_jenkins
  init_conjur
}

########################################
delete_jenkins() {
    if [[ "$($DOCKER ps -a | grep $CLOUDBEES_DEMO_CONTAINER)" == "" ]]; then
      exit 0
    fi
    $DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
	service jenkins stop

#    save_jenkins_state

    echo "Stopping and removing container..."
    $DOCKER stop $CLOUDBEES_DEMO_CONTAINER
    $DOCKER rm $CLOUDBEES_DEMO_CONTAINER
    exit 0
}

########################################
build_jenkins() {
  pushd build
    ./build.sh
  popd
}

########################################
create_volume() {
			# create volume for persistence of state across container instances
  if [[ "$($DOCKER volume ls | grep $CLOUDBEES_DEMO_VOLUME)" == "" ]]; then
    $DOCKER volume create $CLOUDBEES_DEMO_VOLUME 
  fi
}

########################################
save_jenkins_state() {
				# tar jenkins home dir state in container,
				# writes tarfile to host disk via WORKDIR mount
    echo "Making backup of Jenkins state to ${PWD}/backup.tar.z..."
    $DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
	tar czf backup.tar.z 			\
	  $CLOUDBEES_JENKINS_HOME/support	\
	  $CLOUDBEES_JENKINS_HOME/com.cloudbees.jenkins.support.filter.ContentMappings.xml	\
	  $CLOUDBEES_JENKINS_HOME/user-activity	\
	  $CLOUDBEES_JENKINS_HOME/updates	\
	  $CLOUDBEES_JENKINS_HOME/.lastStarted	\
	  $CLOUDBEES_JENKINS_HOME/config.xml	\
	  $CLOUDBEES_JENKINS_HOME/hudson.model.UpdateCenter.xml	\
	  $CLOUDBEES_JENKINS_HOME/com.cloudbees.jenkins.plugins.license.RegistrationStateConfiguration.xml	\
	  $CLOUDBEES_JENKINS_HOME/messaging.t		\
	  $CLOUDBEES_JENKINS_HOME/nodeMonitors.xml	\
	  $CLOUDBEES_JENKINS_HOME/cb-envelope		\
	  $CLOUDBEES_JENKINS_HOME/queue.xml.bak		\
	  $CLOUDBEES_JENKINS_HOME/secrets
}

########################################
restore_jenkins_state() {
  if test -e ${PWD}${WORKDIR}/backup.tar.z ; then
    $DOCKER exec $CLOUDBEES_DEMO_CONTAINER bash -c "cd /; tar xvf $WORKDIR/backup.tar.z"
  fi
}

########################################
create_volume() {
  if [[ "$($DOCKER volume ls | grep $CLOUDBEES_DEMO_VOLUME)" == "" ]]; then
    $DOCKER volume create 	\
	--opt size=300m		\
	 $CLOUDBEES_DEMO_VOLUME 
  fi
}

########################################
start_jenkins() {

  create_volume		# create volume for persistence of state across container instances

  # WORKDIR is assumed to be a subdirectory of current directory.
  # It is mounted at the mountpount w/ same name in container.
  if [[ "$($DOCKER ps | grep $CLOUDBEES_DEMO_CONTAINER)" == "" ]]; then
    cp $LEADER_CERT_FILE .$WORKDIR/conjur-cert.pem
    $DOCKER run -d 							\
      --hostname cbjenkins						\
      --name $CLOUDBEES_DEMO_CONTAINER 					\
      --add-host "$CONJUR_LEADER_HOSTNAME:$CONJUR_LEADER_HOST_IP"	\
      -e "CONJUR_LEADER_HOSTNAME=$CONJUR_LEADER_HOSTNAME"		\
      -e "CONJUR_ACCOUNT=$CONJUR_ACCOUNT"				\
      -e "CONJUR_APPLIANCE_URL=$CONJUR_APPLIANCE_URL"			\
      -e "CONJUR_AUTHN_LOGIN=admin"					\
      -e "CONJUR_AUTHN_API_KEY=$CONJUR_AUTHN_API_KEY"			\
      -e "CONJUR_CERT_FILE=$WORKDIR/conjur-cert.pem"			\
      -e "TERM=xterm" 							\
      -p "50000:8080"							\
      --mount "type=bind,src=${PWD}${WORKDIR},dst=${WORKDIR}"		\
      --mount "src=$CLOUDBEES_DEMO_VOLUME,dst=$CLOUDBEES_JENKINS_HOME"	\
      --restart always 							\
      --entrypoint "sh" 						\
      $CLOUDBEES_DEMO_IMAGE						\
      -c "sleep infinity"

#    restore_jenkins_state

    $DOCKER exec $CLOUDBEES_DEMO_CONTAINER 	\
	service jenkins start
						# shell for keytool must be interactive
    $DOCKER exec -it $CLOUDBEES_DEMO_CONTAINER	\
	keytool -importcert -alias conjur -keystore $KEYSTORE -file $WORKDIR/conjur-cert.pem

    rm $WORKDIR/demo.out
    chmod a+w $WORKDIR/demo.out
  fi
  echo "Waiting for Jenkins to start up..."
  sleep 20 
  echo
  echo -n "Initial Jenkins admin password: "
  echo $($DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
		cat /var/lib/jenkins/secrets/initialAdminPassword)
  echo
}

########################################
init_conjur() {
  $DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
	cybr conjur logon-non-interactive
  $DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
  	cybr conjur append-policy -b root -f ./policy.yml
  JENKINS_HOST_API_KEY=$($DOCKER exec $CLOUDBEES_DEMO_CONTAINER \
				cybr conjur rotate-api-key -l host/$JENKINS_HOSTNAME)
  echo "JENKINS_HOST_API_KEY:" $JENKINS_HOST_API_KEY
}

main "$@"
