apiVersion: v1
data:
  CLUSTER_AUTHN_ID: mac-k8s
  CONJUR_ACCOUNT: dev
  CONJUR_APPLIANCE_URL: https://conjur-follower.cyberark.svc.cluster.local
  CONJUR_AUTHN_TOKEN_FILE: /run/conjur/access-token
  CONJUR_AUTHN_URL: https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/mac-k8s
  CONJUR_FOLLOWER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDfjCCAmagAwIBAgIUIF0uAf4dbNtwXAAeJaPk7Fd0o1AwDQYJKoZIhvcNAQEL
    BQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM
    FmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIwMzMwMTkzNTQ4WhcNMzIwMzI3
    MTkzNTQ4WjAaMRgwFgYDVQQDDA9jb25qdXItZm9sbG93ZXIwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQC7iE6fgQtYGLVlcTRFDlOU84haqhJBzC30lC/6
    cqZgwtFRc7YSjhmJ9kHZtOKwaqssN+HtOgPv4fsFW6RIf2WClK0C1ZteaO7ktOSv
    jFW8uxbBUkTjz0aA6BW4Gg1ZIIlHPF0RS2I7+nNsKuA3X1Yoj5yKfZR1LMZzHWYw
    pHwFm8VbWimd/F7qMvhQmg9nmMAea8eWLv3uFO+TE0tmK4lOcRH+UqzN03TDe8eg
    nsBFxvFfaHWjii1IRfqAAT6jLKTZpA8NuzJeyVk6IJndkQBlBh+xlUNy+m1+oODM
    UtXRQNXom6aBCq5YxSwv+s8OTk13z6PBM7bw8IY/4F1rEl2nAgMBAAGjgZIwgY8w
    DgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBTaOaPuXmtLDTJVv++VYBiQr9gHCTBe
    BgNVHREEVzBVgg9jb25qdXItZm9sbG93ZXKCKmNvbmp1ci1mb2xsb3dlci5jeWJl
    cmFyay5zdmMuY2x1c3Rlci5sb2NhbIIWY29uanVyLW1hc3Rlci1taW5pa3ViZTAN
    BgkqhkiG9w0BAQsFAAOCAQEANv1S+pvRBKP/3AHsjzoIkYGFMwiz3zCAlVkbwFa5
    w7PJ2pGMeqHLmYvJCRhFXuXpgTy32AkUr6asaQKSslyGfCfIsAL7kPXiAfaHoAgM
    kmtrC7nvBaSOBL0a/sXRJXE4teoosB1waZMoExPSUYzqGhi/jNCLneS/P9F2thhz
    QvQGNtuWyw2Hp99sU4KRIwxBylpuwZVbAFtlWlEuBRgQt87cu1d5LOR3IwQX1bmO
    6JWfdYaOEQOAsMGXc23JATgAI1h6bHSAwoxIqsnYc5kWgDDlFAu9yDno5/V9auvQ
    z8zO06HqBR9y5F7vqK/GVV3MZUiq/1562uAbR7UsJ0j96w==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsjCCApqgAwIBAgIJAOttDeW83fjSMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz
    dGVyLW1pbmlrdWJlMB4XDTIyMDMzMDE5MzQzMVoXDTMyMDMyNzE5MzQzMVowQzEM
    MAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1
    ci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDI5MMcUdCEOM3n3ZigB4s5dCo434WLFa+mzijnEuzFsgsK16G4Ha8gxxs9RfpM
    wVC/or6B+H1j0zQ2L55xPgIQh0/irbn4uhzY3jlJhYPOysCBaNvjypNw8h4zJf2S
    pYQzwNW+6m4GRe6ZV7S84mWF2AEkyW6IQFW1OAaEHd8qFeW+RBr4UCwUILSHeNme
    PNjESysxiL7WFoTx+LhpU+raf87STg2PtvG6YrJT8NpLSED0SCs7dK1Vfs1nFJML
    HjXAN3DjOk/PY+Nf53YERrfbMd9i6/+pJAQUROxm9EvP8VMRWcSpWa2eX7W1zDwd
    WNAMt1tNxjI7yrnwC32xdjhXAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy
    LW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy
    LW1hc3RlcjAdBgNVHQ4EFgQUUIx6d61T5Ueva7nTRhPttl7VXKMwHwYDVR0jBBgw
    FoAUUIx6d61T5Ueva7nTRhPttl7VXKMwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
    AeYwDQYJKoZIhvcNAQELBQADggEBAIldoDAo4W3RM2/kRYyDdshUt/k6w5xrtWZZ
    JT6TUIuzIVaiRKi713hJEbVRhiadk29N/rozrMhT5+LdLlMALxIljpveezQRv8A1
    wLyW5j7zEPbJCHvQmPuoh4a5BKm+jjoUhL3LfO4kTNBEepfRTvTgoZPT6ZOB0eoT
    97Jjv/tEV4inu/McsWm3Vyw2AocEl4T1paEXJ0clkMzKVQwjqm1grf6qQsKkrBik
    ucjN8+9mbFy592uFoCYJIha1bo+ZH/wT6sGJ0HsqqqZdOOo1WAw21QyC1ZIpR82k
    /DUP9lRnYzJ/yXUNnD8yO65aIItlqz88AtfT8QCK/Q3dXVYZwlA=
    -----END CERTIFICATE-----
  CONJUR_LEADER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDbTCCAlWgAwIBAgIUGk3yVTS3d7XAPBhjiq3eCX2mxIowDQYJKoZIhvcNAQEL
    BQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM
    FmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIwMzMwMTkzNDMzWhcNMzIwMzI3
    MTkzNDMzWjAhMR8wHQYDVQQDDBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzYUU94fGPzWZGDNc7On7UBQp5tlG
    WTMv9mPD/cGol/Vs/dBrSJL8L8E05/v4Y7dOcIGMdk7FQ8OuRk06mtjqmi5sV070
    LZ9ltKEkfhQsnTe6YaOiSF65nMfvphtcgtrY4MvJS/fnFbEiY0hQbIin1HmkRyZN
    oYNCQGPkVg8hIQkpprfARCX5bd4+kNCUYgPc+/9T6doMj+Ym0cjzWDFYLlV2+s0g
    +eaiKRXC+gPs0DKSRg67d5ffDAcZ9LoY9R89oS/uQnPa4e7O2YB6M8TqqkgY+5ns
    JDI+7whwbhmeTzJQSk0ZRI2VgRsigwG/+0nGLpB3QPZ/tMCR2po256C5iwIDAQAB
    o3sweTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFNo5o+5ea0sNMlW/75VgGJCv
    2AcJMEgGA1UdEQRBMD+CFmNvbmp1ci1tYXN0ZXItbWluaWt1YmWCFmNvbmp1ci1t
    YXN0ZXItbWluaWt1YmWCDWNvbmp1ci1tYXN0ZXIwDQYJKoZIhvcNAQELBQADggEB
    ADZRY0sH4tNb2rfNjLXDoqa0P31IXpaJpBztX1k9AerYuymKm875PM1tMxl14oVc
    vYcZpDs8Bou9CBb61nqVW5JIk7SXnWXp8h33BlZcHReNQI2PZ45VRd4FIDCM5TXE
    8pCCOA7Q3wy/RMZAsCuaULuiBHuSuuDMMm0ShRL1XUQ9qF5l5Li0QLIKIaMLXL1i
    jsrHlxXqPqs9t5YpFwiAceGlo3Nq5cEtZWZX/ctkC51V2N9lGWf5SNOnYDghOlmh
    +3KZ+7JAmuU2AeQpB0IpW/wTFaJO94N4QnhcJuCNqEs5L5G0TQ6382aFHfl1P6g1
    z2sOoRkLpASCzmzkhksgapU=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDsjCCApqgAwIBAgIJAOttDeW83fjSMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV
    BAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz
    dGVyLW1pbmlrdWJlMB4XDTIyMDMzMDE5MzQzMVoXDTMyMDMyNzE5MzQzMVowQzEM
    MAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1
    ci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDI5MMcUdCEOM3n3ZigB4s5dCo434WLFa+mzijnEuzFsgsK16G4Ha8gxxs9RfpM
    wVC/or6B+H1j0zQ2L55xPgIQh0/irbn4uhzY3jlJhYPOysCBaNvjypNw8h4zJf2S
    pYQzwNW+6m4GRe6ZV7S84mWF2AEkyW6IQFW1OAaEHd8qFeW+RBr4UCwUILSHeNme
    PNjESysxiL7WFoTx+LhpU+raf87STg2PtvG6YrJT8NpLSED0SCs7dK1Vfs1nFJML
    HjXAN3DjOk/PY+Nf53YERrfbMd9i6/+pJAQUROxm9EvP8VMRWcSpWa2eX7W1zDwd
    WNAMt1tNxjI7yrnwC32xdjhXAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy
    LW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy
    LW1hc3RlcjAdBgNVHQ4EFgQUUIx6d61T5Ueva7nTRhPttl7VXKMwHwYDVR0jBBgw
    FoAUUIx6d61T5Ueva7nTRhPttl7VXKMwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC
    AeYwDQYJKoZIhvcNAQELBQADggEBAIldoDAo4W3RM2/kRYyDdshUt/k6w5xrtWZZ
    JT6TUIuzIVaiRKi713hJEbVRhiadk29N/rozrMhT5+LdLlMALxIljpveezQRv8A1
    wLyW5j7zEPbJCHvQmPuoh4a5BKm+jjoUhL3LfO4kTNBEepfRTvTgoZPT6ZOB0eoT
    97Jjv/tEV4inu/McsWm3Vyw2AocEl4T1paEXJ0clkMzKVQwjqm1grf6qQsKkrBik
    ucjN8+9mbFy592uFoCYJIha1bo+ZH/wT6sGJ0HsqqqZdOOo1WAw21QyC1ZIpR82k
    /DUP9lRnYzJ/yXUNnD8yO65aIItlqz88AtfT8QCK/Q3dXVYZwlA=
    -----END CERTIFICATE-----
  CONJUR_LEADER_HOSTNAME: conjur-master-minikube
  CONJUR_LEADER_PORT: "443"
  CONJUR_LEADER_URL: https://conjur-master-minikube:443
  CONJUR_VERSION: "5"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CLUSTER_AUTHN_ID":"mac-k8s","CONJUR_ACCOUNT":"dev","CONJUR_APPLIANCE_URL":"https://conjur-follower.cyberark.svc.cluster.local","CONJUR_AUTHN_TOKEN_FILE":"/run/conjur/access-token","CONJUR_AUTHN_URL":"https://conjur-follower.cyberark.svc.cluster.local/api/authn-k8s/mac-k8s","CONJUR_FOLLOWER_CERTIFICATE":"-----BEGIN CERTIFICATE-----\nMIIDfjCCAmagAwIBAgIUIF0uAf4dbNtwXAAeJaPk7Fd0o1AwDQYJKoZIhvcNAQEL\nBQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM\nFmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIwMzMwMTkzNTQ4WhcNMzIwMzI3\nMTkzNTQ4WjAaMRgwFgYDVQQDDA9jb25qdXItZm9sbG93ZXIwggEiMA0GCSqGSIb3\nDQEBAQUAA4IBDwAwggEKAoIBAQC7iE6fgQtYGLVlcTRFDlOU84haqhJBzC30lC/6\ncqZgwtFRc7YSjhmJ9kHZtOKwaqssN+HtOgPv4fsFW6RIf2WClK0C1ZteaO7ktOSv\njFW8uxbBUkTjz0aA6BW4Gg1ZIIlHPF0RS2I7+nNsKuA3X1Yoj5yKfZR1LMZzHWYw\npHwFm8VbWimd/F7qMvhQmg9nmMAea8eWLv3uFO+TE0tmK4lOcRH+UqzN03TDe8eg\nnsBFxvFfaHWjii1IRfqAAT6jLKTZpA8NuzJeyVk6IJndkQBlBh+xlUNy+m1+oODM\nUtXRQNXom6aBCq5YxSwv+s8OTk13z6PBM7bw8IY/4F1rEl2nAgMBAAGjgZIwgY8w\nDgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBTaOaPuXmtLDTJVv++VYBiQr9gHCTBe\nBgNVHREEVzBVgg9jb25qdXItZm9sbG93ZXKCKmNvbmp1ci1mb2xsb3dlci5jeWJl\ncmFyay5zdmMuY2x1c3Rlci5sb2NhbIIWY29uanVyLW1hc3Rlci1taW5pa3ViZTAN\nBgkqhkiG9w0BAQsFAAOCAQEANv1S+pvRBKP/3AHsjzoIkYGFMwiz3zCAlVkbwFa5\nw7PJ2pGMeqHLmYvJCRhFXuXpgTy32AkUr6asaQKSslyGfCfIsAL7kPXiAfaHoAgM\nkmtrC7nvBaSOBL0a/sXRJXE4teoosB1waZMoExPSUYzqGhi/jNCLneS/P9F2thhz\nQvQGNtuWyw2Hp99sU4KRIwxBylpuwZVbAFtlWlEuBRgQt87cu1d5LOR3IwQX1bmO\n6JWfdYaOEQOAsMGXc23JATgAI1h6bHSAwoxIqsnYc5kWgDDlFAu9yDno5/V9auvQ\nz8zO06HqBR9y5F7vqK/GVV3MZUiq/1562uAbR7UsJ0j96w==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIDsjCCApqgAwIBAgIJAOttDeW83fjSMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV\nBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz\ndGVyLW1pbmlrdWJlMB4XDTIyMDMzMDE5MzQzMVoXDTMyMDMyNzE5MzQzMVowQzEM\nMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1\nci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\nAQDI5MMcUdCEOM3n3ZigB4s5dCo434WLFa+mzijnEuzFsgsK16G4Ha8gxxs9RfpM\nwVC/or6B+H1j0zQ2L55xPgIQh0/irbn4uhzY3jlJhYPOysCBaNvjypNw8h4zJf2S\npYQzwNW+6m4GRe6ZV7S84mWF2AEkyW6IQFW1OAaEHd8qFeW+RBr4UCwUILSHeNme\nPNjESysxiL7WFoTx+LhpU+raf87STg2PtvG6YrJT8NpLSED0SCs7dK1Vfs1nFJML\nHjXAN3DjOk/PY+Nf53YERrfbMd9i6/+pJAQUROxm9EvP8VMRWcSpWa2eX7W1zDwd\nWNAMt1tNxjI7yrnwC32xdjhXAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy\nLW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy\nLW1hc3RlcjAdBgNVHQ4EFgQUUIx6d61T5Ueva7nTRhPttl7VXKMwHwYDVR0jBBgw\nFoAUUIx6d61T5Ueva7nTRhPttl7VXKMwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC\nAeYwDQYJKoZIhvcNAQELBQADggEBAIldoDAo4W3RM2/kRYyDdshUt/k6w5xrtWZZ\nJT6TUIuzIVaiRKi713hJEbVRhiadk29N/rozrMhT5+LdLlMALxIljpveezQRv8A1\nwLyW5j7zEPbJCHvQmPuoh4a5BKm+jjoUhL3LfO4kTNBEepfRTvTgoZPT6ZOB0eoT\n97Jjv/tEV4inu/McsWm3Vyw2AocEl4T1paEXJ0clkMzKVQwjqm1grf6qQsKkrBik\nucjN8+9mbFy592uFoCYJIha1bo+ZH/wT6sGJ0HsqqqZdOOo1WAw21QyC1ZIpR82k\n/DUP9lRnYzJ/yXUNnD8yO65aIItlqz88AtfT8QCK/Q3dXVYZwlA=\n-----END CERTIFICATE-----\n","CONJUR_LEADER_CERTIFICATE":"-----BEGIN CERTIFICATE-----\nMIIDbTCCAlWgAwIBAgIUGk3yVTS3d7XAPBhjiq3eCX2mxIowDQYJKoZIhvcNAQEL\nBQAwQzEMMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMM\nFmNvbmp1ci1tYXN0ZXItbWluaWt1YmUwHhcNMjIwMzMwMTkzNDMzWhcNMzIwMzI3\nMTkzNDMzWjAhMR8wHQYDVQQDDBZjb25qdXItbWFzdGVyLW1pbmlrdWJlMIIBIjAN\nBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzYUU94fGPzWZGDNc7On7UBQp5tlG\nWTMv9mPD/cGol/Vs/dBrSJL8L8E05/v4Y7dOcIGMdk7FQ8OuRk06mtjqmi5sV070\nLZ9ltKEkfhQsnTe6YaOiSF65nMfvphtcgtrY4MvJS/fnFbEiY0hQbIin1HmkRyZN\noYNCQGPkVg8hIQkpprfARCX5bd4+kNCUYgPc+/9T6doMj+Ym0cjzWDFYLlV2+s0g\n+eaiKRXC+gPs0DKSRg67d5ffDAcZ9LoY9R89oS/uQnPa4e7O2YB6M8TqqkgY+5ns\nJDI+7whwbhmeTzJQSk0ZRI2VgRsigwG/+0nGLpB3QPZ/tMCR2po256C5iwIDAQAB\no3sweTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFNo5o+5ea0sNMlW/75VgGJCv\n2AcJMEgGA1UdEQRBMD+CFmNvbmp1ci1tYXN0ZXItbWluaWt1YmWCFmNvbmp1ci1t\nYXN0ZXItbWluaWt1YmWCDWNvbmp1ci1tYXN0ZXIwDQYJKoZIhvcNAQELBQADggEB\nADZRY0sH4tNb2rfNjLXDoqa0P31IXpaJpBztX1k9AerYuymKm875PM1tMxl14oVc\nvYcZpDs8Bou9CBb61nqVW5JIk7SXnWXp8h33BlZcHReNQI2PZ45VRd4FIDCM5TXE\n8pCCOA7Q3wy/RMZAsCuaULuiBHuSuuDMMm0ShRL1XUQ9qF5l5Li0QLIKIaMLXL1i\njsrHlxXqPqs9t5YpFwiAceGlo3Nq5cEtZWZX/ctkC51V2N9lGWf5SNOnYDghOlmh\n+3KZ+7JAmuU2AeQpB0IpW/wTFaJO94N4QnhcJuCNqEs5L5G0TQ6382aFHfl1P6g1\nz2sOoRkLpASCzmzkhksgapU=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIDsjCCApqgAwIBAgIJAOttDeW83fjSMA0GCSqGSIb3DQEBCwUAMEMxDDAKBgNV\nBAoMA2RldjESMBAGA1UECwwJQ29uanVyIENBMR8wHQYDVQQDDBZjb25qdXItbWFz\ndGVyLW1pbmlrdWJlMB4XDTIyMDMzMDE5MzQzMVoXDTMyMDMyNzE5MzQzMVowQzEM\nMAoGA1UECgwDZGV2MRIwEAYDVQQLDAlDb25qdXIgQ0ExHzAdBgNVBAMMFmNvbmp1\nci1tYXN0ZXItbWluaWt1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB\nAQDI5MMcUdCEOM3n3ZigB4s5dCo434WLFa+mzijnEuzFsgsK16G4Ha8gxxs9RfpM\nwVC/or6B+H1j0zQ2L55xPgIQh0/irbn4uhzY3jlJhYPOysCBaNvjypNw8h4zJf2S\npYQzwNW+6m4GRe6ZV7S84mWF2AEkyW6IQFW1OAaEHd8qFeW+RBr4UCwUILSHeNme\nPNjESysxiL7WFoTx+LhpU+raf87STg2PtvG6YrJT8NpLSED0SCs7dK1Vfs1nFJML\nHjXAN3DjOk/PY+Nf53YERrfbMd9i6/+pJAQUROxm9EvP8VMRWcSpWa2eX7W1zDwd\nWNAMt1tNxjI7yrnwC32xdjhXAgMBAAGjgagwgaUwSAYDVR0RBEEwP4IWY29uanVy\nLW1hc3Rlci1taW5pa3ViZYIWY29uanVyLW1hc3Rlci1taW5pa3ViZYINY29uanVy\nLW1hc3RlcjAdBgNVHQ4EFgQUUIx6d61T5Ueva7nTRhPttl7VXKMwHwYDVR0jBBgw\nFoAUUIx6d61T5Ueva7nTRhPttl7VXKMwDAYDVR0TBAUwAwEB/zALBgNVHQ8EBAMC\nAeYwDQYJKoZIhvcNAQELBQADggEBAIldoDAo4W3RM2/kRYyDdshUt/k6w5xrtWZZ\nJT6TUIuzIVaiRKi713hJEbVRhiadk29N/rozrMhT5+LdLlMALxIljpveezQRv8A1\nwLyW5j7zEPbJCHvQmPuoh4a5BKm+jjoUhL3LfO4kTNBEepfRTvTgoZPT6ZOB0eoT\n97Jjv/tEV4inu/McsWm3Vyw2AocEl4T1paEXJ0clkMzKVQwjqm1grf6qQsKkrBik\nucjN8+9mbFy592uFoCYJIha1bo+ZH/wT6sGJ0HsqqqZdOOo1WAw21QyC1ZIpR82k\n/DUP9lRnYzJ/yXUNnD8yO65aIItlqz88AtfT8QCK/Q3dXVYZwlA=\n-----END CERTIFICATE-----\n","CONJUR_LEADER_HOSTNAME":"conjur-master-minikube","CONJUR_LEADER_PORT":"443","CONJUR_LEADER_URL":"https://conjur-master-minikube:443","CONJUR_VERSION":"5"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"dap-config","namespace":"cyberark"}}
  creationTimestamp: "2022-04-04T19:00:21Z"
  name: dap-config
  namespace: user1
  resourceVersion: "147140"
  uid: a5948bab-a996-41cf-9ac2-7905a862131a
